export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

  // Teacher
  TEACHER_MISSING_FIELDS = "TEACHER_MISSING_FIELDS",
  TEACHER_EMAIL_CONFLICT = "TEACHER_EMAIL_CONFLICT",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  TEACHER_FORBIDDEN = "TEACHER_FORBIDDEN",
  TEACHER_PASSWORD_INVALID = "TEACHER_PASSWORD_INVALID",

  // Experiment
  EXPERIMENT_MISSING_FIELDS = "EXPERIMENT_MISSING_FIELDS",
  EXPERIMENT_PIN_CONFLICT = "EXPERIMENT_PIN_CONFLICT",
  EXPERIMENT_NOT_FOUND = "EXPERIMENT_NOT_FOUND",
  EXPERIMENT_FORBIDDEN = "EXPERIMENT_FORBIDDEN",
  EXPERIMENT_TYPE_MISMATCH = "EXPERIMENT_TYPE_MISMATCH",
  EXPERIMENT_INVALID_UPDATE_FIELD = "EXPERIMENT_INVALID_UPDATE_FIELD",
  EXPERIMENT_FINALIZED = "EXPERIMENT_FINALIZED",
  EXPERIMENT_INVALID_STATUS = "EXPERIMENT_INVALID_STATUS",
  EXPERIMENT_NOT_STARTED = "EXPERIMENT_NOT_STARTED",
  EXPERIMENT_RESULT_NOT_RELEASED = "EXPERIMENT_RESULT_NOT_RELEASED",

  // Response
  RESPONSE_PIN_REQUIRED = "RESPONSE_PIN_REQUIRED",
  RESPONSE_NOT_FOUND = "RESPONSE_NOT_FOUND",
  RESPONSE_INVALID_PAYLOAD = "RESPONSE_INVALID_PAYLOAD",

  // Generic
  BAD_REQUEST = "BAD_REQUEST",
  CONFLICT = "CONFLICT",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL = "INTERNAL",
}

export default ErrorCode;
